### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by CelsoTeixeira** [AnomalyInnovations/serverless-stack-demo-mono-api#2]
Hello, I'm looking at this to try to understand how to handle stack references and it's pretty clear except when we're dealing from references to Environment Variables.

I cloned the project and did the deploy following the order, but the lambdas from notes and users was not getting the correct environment values.

```
  environment:
    tableName:
      ${file(../database/serverless.yml):custom.tableName}
```

I ended up with two changes, on the stack I'am creating the dynamo, I added a new Output:

```
Outputs:
    TableName:
      Value:
        Ref:
          Table
      Export:
        Name: TableName
```

And when I need to reference the dynamo I can use:

```
environment:
    TABLE:
      'Fn::ImportValue': 'TableName'
```

Do you know why this behaviour has changed? Or I'm missing some declaration on the database definition? Thers is no tableName on the custom declaration there.

Thanks for the project, it's was really easy to follow and getting to understand better the stack references.

**Comment by jayair** [comment]
Ah thanks. I see what the issue is. I forgot to make the change to the repo. I had changed it in the chapter - https://serverless-stack.com/chapters/dynamodb-as-a-serverless-service.html

I just made an update now to add the reference to `tableName` - https://github.com/AnomalyInnovations/serverless-stack-demo-mono-api/commit/d2b6b9c067a13f9fa1e65e3965b8426e2bf9a6a8

Let me know if that makes sense.

**Comment by CelsoTeixeira** [comment]
Ah nice, thanks for the response! It's all connected now.
